export const SUB_CATEGORY_DATA: Record<string, {id: string}[]> = {
    NBA: [
        {id: "Atlanta Hawks"},
        {id: "Boston Celtics"},
        {id: "Brooklyn Nets"},
        {id: "Charlotte Hornets"},
        {id: "Chicago Bulls"},
        {id: "Cleveland Cavaliers"},
        {id: "Dallas Mavericks"},
        {id: "Denver Nuggets"},
        {id: "Detroit Pistons"},
        {id: "Golden State Warriors"},
        {id: "Houston Rockets"},
        {id: "Indiana Pacers"},
        {id: "LA Clippers"},
        {id: "Los Angeles Lakers"},
        {id: "Memphis Grizzlies"},
        {id: "Miami Heat"},
        {id: "Milwaukee Bucks"},
        {id: "Minnesota Timberwolves"},
        {id: "New Orleans Pelicans"},
        {id: "New York Knicks"},
        {id: "Oklahoma City Thunder"},
        {id: "Orlando Magic"},
        {id: "Philadelphia 76ers"},
        {id: "Phoenix Suns"},
        {id: "Portland Trail Blazers"},
        {id: "Sacramento Kings"},
        {id: "San Antonio Spurs"},
        {id: "Toronto Raptors"},
        {id: "Utah Jazz"},
        {id: "Washington Wizards"}
    ],
    NFL: [
        { id: "Arizona Cardinals" },
        { id: "Atlanta Falcons" },
        { id: "Baltimore Ravens" },
        { id: "Buffalo Bills" },
        { id: "Carolina Panthers" },
        { id: "Chicago Bears" },
        { id: "Cincinnati Bengals" },
        { id: "Cleveland Browns" },
        { id: "Dallas Cowboys" },
        { id: "Denver Broncos" },
        { id: "Detroit Lions" },
        { id: "Green Bay Packers" },
        { id: "Houston Texans" },
        { id: "Indianapolis Colts" },
        { id: "Jacksonville Jaguars" },
        { id: "Kansas City Chiefs" },
        { id: "Las Vegas Raiders" },
        { id: "Los Angeles Chargers" },
        { id: "Los Angeles Rams" },
        { id: "Miami Dolphins" },
        { id: "Minnesota Vikings" },
        { id: "New England Patriots" },
        { id: "New Orleans Saints" },
        { id: "New York Giants" },
        { id: "New York Jets" },
        { id: "Philadelphia Eagles" },
        { id: "Pittsburgh Steelers" },
        { id: "San Francisco 49ers" },
        { id: "Seattle Seahawks" },
        { id: "Tampa Bay Buccaneers" },
        { id: "Tennessee Titans" },
        { id: "Washington Commanders" }

    ],
    "Big 12 CBB": [
        { id: "Arizona Wildcats" },
        { id: "Arizona State Sun Devils" },
        { id: "Baylor Bears" },
        { id: "BYU Cougars" },
        { id: "Cincinnati Bearcats" },
        { id: "Colorado Buffaloes" },
        { id: "Houston Cougars" },
        { id: "Iowa State Cyclones" },
        { id: "Kansas Jayhawks" },
        { id: "Kansas State Wildcats" },
        { id: "Oklahoma State Cowboys" },
        { id: "TCU Horned Frogs" },
        { id: "Texas Tech Red Raiders" },
        { id: "UCF Knights" },
        { id: "Utah Utes" },
        { id: "West Virginia Mountaineers" }
    ],
    Crypto: [
        { id: 'Aave (AAVE)' },
        { id: 'Aster (ASTER)' },
        { id: 'Avalanche (AVAX)' },
        { id: 'Bitget Token (BGB)' },
        { id: 'Bitcoin (BTC)' },
        { id: 'Bitcoin Cash (BCH)' },
        { id: 'Bittensor (TAO)' },
        { id: 'BNB (BNB)' },
        { id: 'Canton (CC)' },
        { id: 'Cardano (ADA)' },
        { id: 'Chainlink (LINK)' },
        { id: 'Cronos (CRO)' },
        { id: 'Dai (DAI)' },
        { id: 'Dogecoin (DOGE)' },
        { id: 'Ethena (USDe)' },
        { id: 'Ethereum (ETH)' },
        { id: 'Ethereum Classic (ETC)' },
        { id: 'Global Dollar (USDG)' },
        { id: 'Hedera (HBAR)' },
        { id: 'Hyperliquid (HYPE)' },
        { id: 'Internet Computer (ICP)' },
        { id: 'Litecoin (LTC)' },
        { id: 'Mantle (MNT)' },
        { id: 'MemeCore (M)' },
        { id: 'Monero (XMR)' },
        { id: 'MYX Finance (MYX)' },
        { id: 'NEAR Protocol (NEAR)' },
        { id: 'OKB (OKB)' },
        { id: 'PAX Gold (PAXG)' },
        { id: 'PayPal USD (PYUSD)' },
        { id: 'Pepe (PEPE)' },
        { id: 'Pi (PI)' },
        { id: 'Polkadot (DOT)' },
        { id: 'Ripple USD (RLUSD)' },
        { id: 'Shiba Inu (SHIB)' },
        { id: 'Sky (SKY)' },
        { id: 'Solana (SOL)' },
        { id: 'Stellar (XLM)' },
        { id: 'Sui (SUI)' },
        { id: 'Tether (USDT)' },
        { id: 'Tether Gold (XAUt)' },
        { id: 'Toncoin (TON)' },
        { id: 'TRON (TRX)' },
        { id: 'UNUS SED LEO (LEO)' },
        { id: 'Uniswap (UNI)' },
        { id: 'USD Coin (USDC)' },
        { id: 'World Liberty Financial USD (USD1)' },
        { id: 'World Liberty Financial WLFI (WLFI)' },
        { id: 'XRP (XRP)' },
        { id: 'Zcash (ZEC)' },
    ],
    Stocks: [
        { id: 'Alibaba (BABA)' },
        { id: 'Alphabet (GOOGL)' },
        { id: 'Amazon (AMZN)' },
        { id: 'America Movil (AMX)' },
        { id: 'Apple (AAPL)' },
        { id: 'ASML (ASML)' },
        { id: 'Banco de Chile (BCH)' },
        { id: 'Banco Santander-Chile (BSAC)' },
        { id: 'Baidu (BIDU)' },
        { id: 'Bank of America (BAC)' },
        { id: 'Barclays (BCS)' },
        { id: 'Berkshire Hathaway (BRK-A)' },
        { id: 'BHP (BHP)' },
        { id: 'BP (BP)' },
        { id: 'Broadcom (AVGO)' },
        { id: 'Caterpillar (CAT)' },
        { id: 'Cemex SAB de CV (CX)' },
        { id: 'Chevron (CVX)' },
        { id: 'Cisco (CSCO)' },
        { id: 'CMS Energy (CMS)' },
        { id: 'Coca-Cola FEMSA (KOF)' },
        { id: 'Costco (COST)' },
        { id: 'Ecopetrol (EC)' },
        { id: 'Eli Lilly (LLY)' },
        { id: 'ExxonMobil (XOM)' },
        { id: 'FEMSA (FMX)' },
        { id: 'HDFC Bank (HDB)' },
        { id: 'Home Depot (HD)' },
        { id: 'HSBC (HSBC)' },
        { id: 'Johnson & Johnson (JNJ)' },
        { id: 'JPMorgan Chase (JPM)' },
        { id: 'Lloyds (LYG)' },
        { id: 'Mastercard (MA)' },
        { id: 'Micron Technology (MU)' },
        { id: 'Microsoft (MSFT)' },
        { id: 'National Grid (NGG)' },
        { id: 'NetEase (NTES)' },
        { id: 'Netflix (NFLX)' },
        { id: 'Nvidia (NVDA)' },
        { id: 'Oracle (ORCL)' },
        { id: 'Pinduoduo (PDD)' },
        { id: 'Procter & Gamble (PG)' },
        { id: 'Taiwan Semiconductor (TSM)' },
        { id: 'Telkom Indonesia (TLK)' },
        { id: 'Tesla (TSLA)' },
        { id: 'Televisa (TV)' },
        { id: 'Toyota (TM)' },
        { id: 'Visa (V)' },
        { id: 'Vodafone (VOD)' },
        { id: 'Walmart (WMT)' },
    ]
}